"""init subscription database

Revision ID: 58d04c9cba27
Revises:
Create Date: 2025-10-02 17:03:25.856724+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58d04c9cba27"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subscription_plans",
        sa.Column("plan_code", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("stripe_price_id", sa.String(length=512), nullable=True),
        sa.Column("min_seats_for_subscription", sa.Integer(), nullable=False),
        sa.Column("max_seats_for_subscription", sa.Integer(), nullable=False),
        sa.Column("config_max_custom_mcp_servers", sa.Integer(), nullable=False),
        sa.Column("config_log_retention_days", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("plan_code"),
        sa.UniqueConstraint("plan_code"),
    )
    op.create_table(
        "organization_entitlement_overrides",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("seat_count", sa.Integer(), nullable=True),
        sa.Column("max_custom_mcp_servers", sa.Integer(), nullable=True),
        sa.Column("log_retention_days", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("plan_code", sa.String(length=512), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=512), nullable=True),
        sa.Column("stripe_item_id", sa.String(length=512), nullable=True),
        sa.Column("stripe_price_id", sa.String(length=512), nullable=True),
        sa.Column("seat_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PAST_DUE",
                "CANCELLED",
                name="organizationsubscriptionstatus",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["plan_code"],
            ["subscription_plans.plan_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", name="uc_org_plan"),
        sa.UniqueConstraint("stripe_subscription_id", name="uc_stripe_subscription_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_subscriptions")
    op.drop_table("organization_entitlement_overrides")
    op.drop_table("subscription_plans")
    op.drop_table("organizations")
    # ### end Alembic commands ###
