"""creating unique index for shared account, operational account and operatonal MCP Config per Server

Revision ID: 7a6c7afccea1
Revises: a8253e7a0326
Create Date: 2025-09-22 16:32:13.911149+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6c7afccea1'
down_revision: Union[str, None] = 'a8253e7a0326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
