"""add_sharability_to_connected_account_and_mcp_config

Revision ID: aba8ee1e1425
Revises: 63224673a97a
Create Date: 2025-09-04 16:17:57.156149+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba8ee1e1425'
down_revision: Union[str, None] = '63224673a97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns with default values
    op.add_column('connected_accounts', sa.Column('sharability', sa.Enum('INDIVIDUAL', 'SHARED', name='connectedaccountsharability', native_enum=False, length=50), nullable=False, server_default='INDIVIDUAL'))
    op.add_column('mcp_server_configurations', sa.Column('connected_account_sharability', sa.Enum('INDIVIDUAL', 'SHARED', name='connectedaccountsharability', native_enum=False, length=50), nullable=False, server_default='INDIVIDUAL'))

    # Remove default values
    op.alter_column('connected_accounts', 'sharability', server_default=None)
    op.alter_column('mcp_server_configurations', 'connected_account_sharability', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_server_configurations', 'connected_account_sharability')
    op.drop_column('connected_accounts', 'sharability')
    # ### end Alembic commands ###
