name: Database Migration
on:
  workflow_call:
    inputs:
      ecr_repository_url:
        type: string
        description: The ECR repository URL to use
        required: true
      image_tag:
        type: string
        description: The image tag to use
        required: true
      ecs_task_definition:
        type: string
        description: The ECS task definition to use
        required: true
      ecs_cluster:
        type: string
        description: The ECS cluster to deploy to
        required: true
      referenced_network_config_ecs_service:
        type: string
        description: The ECS service to reference for the network configuration
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.CICD_AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Get the container name from the task definition
      # Note, modify this if we have more than one container
      - name: Get current task definition from ECS
        id: get-task-definition-container-name
        run: |
          CONTAINER_NAME=$(aws ecs describe-task-definition \
            --task-definition ${{ inputs.ecs_task_definition }} \
            --query taskDefinition.containerDefinitions[0].name \
            --output text)
          echo "CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_OUTPUT

      # Update the task definition with the new image
      - name: Replace new Image to Task Definition JSON
        id: update-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: ${{ inputs.ecs_task_definition }}
          container-name: ${{ steps.get-task-definition-container-name.outputs.CONTAINER_NAME }}
          image: "${{ inputs.ecr_repository_url }}:${{ inputs.image_tag }}"

      # Obtain the network configuration from referenced ECS service.
      - name: Obtain Referenced Service Network Configuration
        id: get-network-config
        run: |
          NETWORK_CONFIG=$(aws ecs describe-services \
          --cluster ${{ inputs.ecs_cluster }} \
          --services ${{ inputs.referenced_network_config_ecs_service }} \
          --output json \
          | jq -r '.services[0].networkConfiguration | @json')
          echo "NETWORK_CONFIG=${NETWORK_CONFIG}" >> $GITHUB_OUTPUT

      # Run DB migration with the same network configuration
      - name: Run database migrations
        run: |
          aws ecs run-task \
          --task-definition ${{ steps.update-task-definition.outputs.task-definition }} \
          --cluster ${{ inputs.ecs_cluster }} \
          --launch-type="FARGATE" \
          --network-configuration '${{ steps.get-network-config.outputs.NETWORK_CONFIG }}' \
          --count 1

      - name: Wait for migration task to finish
        run: aws ecs wait tasks-stopped --cluster ${{ inputs.ecs_cluster }} --tasks $(aws ecs list-tasks --cluster ${{ inputs.ecs_cluster }} --family ${{ inputs.ecs_task_definition }} --query 'taskArns' --output text)
